Ecommerce.WebApp/Areas/Admin/Controllers/AdministrationController.cs
using Ecommerce.Data.Entities;
using Ecommerce.WebApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce.WebApp.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    [Route("admin/authorization")]
    [Route("admin/auth")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<AppRole> roleManager;

        private readonly UserManager<AppUser> userManager;

        public AdministrationController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [Route("list-roles")]
        [HttpGet]
        public IActionResult ListRoles()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        [Route("create-role")]
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [Route("create-role")]
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppRole appRole = new AppRole
                {
                    Name = model.RoleName,

                    Description = model.Description
                };

                IdentityResult result = await roleManager.CreateAsync(appRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        // Chỉnh sửa các Roles
        [Route("edit-role/{id}")]
        [HttpGet]
        public async Task<IActionResult> EditRole(Guid id)
        {
            // Find the role by Role ID
            var role = await roleManager.FindByIdAsync(id.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in userManager.Users)
            {

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        [Route("edit-role/{id}")]
        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id.ToString());
            if (role == null)
            {
                ViewBag.ErrorMessage =
                    $"Role with Id: {model.Id} could not be found";
                return View("NotFound");
            }

            role.Name = model.RoleName;

            var result = await roleManager.UpdateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("ListRoles");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(model);
        }

        [Route("edit-user-role/{roleId}")]
        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(Guid roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [Route("edit-user-role/{roleId}")]
        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, Guid roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId.ToString());

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }

        [Route("delete-role/{id}")]
        [HttpGet]
        public async Task<IActionResult> DeleteRole(Guid id)
        {
            var role = await roleManager.FindByIdAsync(id.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await roleManager.DeleteAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListRoles");
            }
        }



    }
}

Ecommerce.WebApp/Areas/Admin/Views/Administration/CreateRole.cshtml
@model CreateRoleViewModel

@{
    ViewData["Title"] = "Thêm mới role";
}

<div class="content-wrapper">

    <div class="row">

        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Thêm mới danh mục</h4>
                    <div class="col-md-4">
                        <form asp-action="CreateRole" method="post" id="form">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="RoleName" class="control-label"></label>
                                <input asp-for="RoleName" class="form-control" />
                                <span asp-validation-for="RoleName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="button" value="Create" class="btn btn-primary" onclick="onConfirm()"/>
                            </div>
                        </form>
                    </div>

                    <div>
                        <a asp-action="Index">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
<script>
    function onConfirm() {
        Swal.fire({
          title: 'Thêm mới quyền?',
          text: "Bạn có chắc sẽ thêm quyền này?",
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Xác nhận!'
        }).then((result) => {
          if (result.isConfirmed) {
              $("#form").submit();
            Swal.fire(
              'Thêm thành công!',
              '',
              'success'
            )
          } 
        })
    }


</script>
}

Ecommerce.WebApp/Areas/Admin/Views/Administration/EditRole.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Chỉnh sửa role";
}

<div class="content-wrapper">

    <div class="row">

        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Chỉnh sửa role</h4>

                    <form method="post" class="mt-3 row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="Id" class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="Id" disabled class="form-control">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="RoleName" class="form-control">
                                    <span asp-validation-for="RoleName" class="text-danger"></span>
                                </div>
                            </div>

                            <div asp-validation-summary="All" class="text-danger"></div>

                            <div class="form-group row">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                    <a asp-action="ListRoles" class="btn btn-secondary">Cancel</a>
                                </div>
                            </div>
                            <div class="card-footert pl-0 ml-0">
                                <a asp-controller="Administration" asp-action="EditUsersInRole"
                                   asp-route-roleId="@Model.Id" class="btn btn-primary">
                                   Phân quyền user cho role này
                                </a>
                            </div>
                        </div>
                        
                    </form>

                </div>
            </div>
        </div>
    </div>    </div>

Ecommerce.WebApp/Areas/Admin/Views/Administration/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{
    var roleId = ViewBag.roleId;
}

<div class="content-wrapper">

    <div class="row">

        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Phân quyền cho user</h4>
                    <form method="post" class="p-3">

                        @for (int i = 0; i < Model.Count; i++)
                        {
                            <div class="form-check m-1">
                                <input type="hidden" asp-for="@Model[i].UserId" />
                                <input type="hidden" asp-for="@Model[i].UserName" />
                                <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                                <label class="form-check-label" asp-for="@Model[i].IsSelected">
                                    @Model[i].UserName
                                </label>
                            </div>
                        }

                        <input type="submit" value="Update" class="btn btn-primary mt-3"
                               style="width:auto" />
                        <a asp-action="EditRole" asp-route-id="@roleId"
                           class="btn btn-secondary mt-3" style="width:auto">Cancel</a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Ecommerce.WebApp/Areas/Admin/Views/Administration/ListRoles.cshtml
@model IEnumerable<Ecommerce.Data.Entities.AppRole>

@{
    ViewData["Title"] = "Tất cả roles";
}
<div class="content-wrapper">

    <div class="row">

        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Quản lý quyền</h4>
                    <p class="card-description">
                        <code><a asp-action="CreateRole">Thêm mới</a></code>
                    </p>

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Name)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Description)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @item.Id
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Description)
                                            </td>
                                            <td>
                                                <a asp-action="EditRole" asp-route-Id="@item.Id">Sửa</a>
                                                <button type="button" class="text-danger" onclick="deleteItem('@item.Id')" style="background: transparent; border: none; font-weight: 700; ">Xóa</button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    input.btn.btn-danger {
    position: absolute;
    right: 25px;
    top: 25px;
}
th { font-weight: 700!important}
</style>

<script>
    function deleteItem(id) {
        Swal.fire({
          title: 'Xác nhận xóa?',
          text: "Bạn có chắc sẽ xóa role này?",
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Xóa!'
        }).then((result) => {
          if (result.isConfirmed) {
              window.location.href = '/admin/auth/delete-role/' + id;
            Swal.fire(
              'Xóa thành công!',
              '',
              'success'
            )
          }
        })
    }
</script>